export const NUMBER_INPUT = 'NUMBER_INPUT';
export const NUMBER_SIGNED_INPUT = 'NUMBER_SIGNED_INPUT';
export const OPERATION_INPUT = 'OPERATION_INPUT';
export const UNDO = 'UNDO';
export const CALCULATE = 'CALCULATE';
